// <auto-generated />
namespace And.Ecommerce.Core.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Crate_ProductImages_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Crate_ProductImages_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201912080806302_Crate_ProductImages_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
