// <auto-generated />
namespace And.Ecommerce.Core.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_VerificationCode_and_IsEmailVerified_to_users_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_VerificationCode_and_IsEmailVerified_to_users_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201912071400571_add_VerificationCode_and_IsEmailVerified_to_users_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
